### ISSUE TITLE
BK800L release

### ISSUE THREAD

**Issue by Dalmanos** [tomaskovacik/kicad-library#1]
Nice to see someone's working on adding the cheap bk800l audio module to the kicad library!
I'm going to need it in an ongoing project of myself, it would be great to be able to use your solution
instead of creating my own one.
Do you have an idea when you want to finish the part?
Thanks for sharing your efforts!

I browsed your website a little bit, you seem to be an interesting person :)

**Comment by tomaskovacik** [comment]
i have it all it's F-6188 module, but forgot to make git push ;) so any minute :)

**Comment by tomaskovacik** [comment]
it's there :) also I have in todo C library (avr/stm/.... ) for this module(s)
