### ISSUE TITLE
BK8000L flash chip

### ISSUE THREAD

**Issue by Arroquw** [tomaskovacik/kicad-library#10]
Hi, my module has a flash chip named "boyamicro 25q40astig". Is there any way to flash this one?

**Comment by tomaskovacik** [comment]
this is not the right place to as ask the question if flashrom can read/write to specific flash chip. Check flashrom site and if it is not supported, you must write patch based on datasheet for your flashchip.

https://www.flashrom.org/Supported_hardware

http://www.boyamicro.com/English/Product/6825041859.html
