### ISSUE TITLE
Possible to flash BK8000L Firmware with Arduino?

### ISSUE THREAD

**Issue by harryberlin** [tomaskovacik/kicad-library#11]
I have this BK8000L Device from aliexpress.
But the serial pins are not working.
Is there a way to flash an other firmware with an Arduino, to get it working?
Is there a tutorial how to flash?

https://de.aliexpress.com/item/32822568811.html
![grafik](https://user-images.githubusercontent.com/13656586/109390944-d7b1e980-7914-11eb-98ad-498aef8b3c5a.png)

**Comment by tomaskovacik** [comment]
yes, arduino can by used as programer for flashrom, and flashrom is used to flash chip on bk8000L module:
https://kovo-blog.blogspot.com/2017/11/bk8000l-change-name.html
https://www.flashrom.org/Serprog/Arduino_flasher

**Comment by harryberlin** [comment]
thank you for your answer.
have seen there is a solution for raspberry. would be more easy, in case of 3.3V.

**Comment by DrSaad77** [comment]
I am interested by flashing chip of BK8000L, I wish to change Name and install a better bin or Firmware.
Unfortunaly I do not understand how to do that on the software part. Never flashed a chip. Need Linux ou can use Windows please??
I use to flash code to arduino Pro Mini and Pro Micro , using this programmer: CP2102 programmer 6 in 1
https://fr.aliexpress.com/item/32871206407.html

From infos, I collected around, it is possible I guess, with a programmer that got CH341, may I guess this one also.
I can handle connection part, but kind of lost on PC part, about tools and step to follows, nebby in chip......
Thx you very much if someone can help, or maybe share a tuto, it will be greatly apprecieted ))
Thx guys

**Comment by tomaskovacik** [comment]
CP2102 is UART to USB adapter, not programer. 
for programing flashrom on bk8000l module you need flash programer, but arduino can be used, check my blog post, link in prev. post

**Comment by DrSaad77** [comment]
> CP2102 is UART to USB adapter, not programer. 
> for programing flashrom on bk8000l module you need flash programer, but arduino can be used, check my blog post, link in prev. post

Thx you very much ))
Sorry for confusion, new to flash chip.
I got Arduino Nano, and a UNO available.
I know the link, but kind of lost in it. 
thx for the group on Gmail or forum kind, a lot of good stuff are shared there 👍🏻

**Comment by tomaskovacik** [comment]
this is site about using arduino as programer for flash: https://www.flashrom.org/Serprog/Arduino_flasher, when you build one you can follow my blog post about changing name

**Comment by DrSaad77** [comment]
Thx you very much, good info and lot of explanation for newbies ehehe
Hope now gona be able to change the name, fingers crossed ))
