### ISSUE TITLE
Issue with flashing FT25H04 to activate serial communication on BK8000L

### ISSUE THREAD

**Issue by FrederikSchoofs** [tomaskovacik/kicad-library#12]
Hi,

I have a BK8000L and I am trying to use it with your library.
The serial communication is not working. Same issue as here:
https://github.com/tomaskovacik/BK8000L/issues/12
I assume uart is also not enabled on my chip.

I tried to re-write the flash following your blog post
https://kovo-blog.blogspot.com/2017/11/bk8000l-change-name.html

However for me, Flashrom states that this binary file:
https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/F-6188_BK8000L/bins/firmware_serial.bin
is too large for the FT25H04 chip. 
The following error message is shown: "Image size (524394 B) doesn't match the flash chip's size (524288 B)"

I then tried with this flash file:
https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/F-6188_BK8000L/BK8000L.flash
I was able to flash this file to the chip as its size is 524288 B, but this doesn't seem to solve my serial comm issue.

What is the difference between F-6188_BK8000L/bins/firmware_serial.bin and /F-6188_BK8000L/BK8000L.flash?
Any idea how I should get the correct flash on my chip to activate the serial communication?

Thanks

**Comment by tomaskovacik** [comment]
try this one: https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/F-6188_BK8000L/my_flash_working_serial_audio_phone.bin

**Comment by FrederikSchoofs** [comment]
I am able to flash it. But serial comm issue remains.

I connect it to an arduino uno, and run your example from here: https://github.com/tomaskovacik/BK8000L 
with software serial.

I get this output and none of the commands work

⸮⸮"⸮press h for help
Bluetooth disconnected
Music stoped
Module OFF

**Comment by tomaskovacik** [comment]
that flash works for 100%, i use it in car with mcu to communicate with it, check your wiring.t.

**Comment by FrederikSchoofs** [comment]
I tried some more and now it seems to be working with that flash file!

Thanks for the quick response and help!

**Comment by tomaskovacik** [comment]
you are welcome :)
