### ISSUE TITLE
Firmware configuration

### ISSUE THREAD

**Issue by ChrisHughes** [tomaskovacik/kicad-library#4]
I've written the firmware bin file to a BK8000L module to get AT commands working, and am finding that I'm getting a battery low warning on connection with an android device. This did not happen previously. Is there any reference of hex values to change for configuring these various features? As a battery warning message is not helpful on a non-battery powered device, such as in a car radio.

**Comment by tomaskovacik** [comment]
Are you using 3v3 power supply?On 13 Feb 2019 02:33, ChrisHughes <notifications@github.com> wrote:I've written the firmware bin file to a BK8000L module to get AT commands working, and am finding that I'm getting a battery low warning on connection with an android device. This did not happen previously. Is there any reference of hex values to change for configuring these various features? As a battery warning message is not helpful on a non-battery powered device, such as in a car radio.

**Comment by ChrisHughes** [comment]
Yes I am using a regulated 3.3v supply. I should clarify the older firmware_noserial does not give this warning. The new firmware with at commands does give this warning. Is this a property or setting in the 41000 block of memory?

**Comment by tomaskovacik** [comment]
hello, I really do not know, you must test it : 

download this app: https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/F-6888_bk3254/BEKEN_JTAG_bk3254/3254_ToolKit2.6.exe

set some voltages and save, then compare hex files so you find where it is set, and then look at your original firmware and one you flashed, or:

check what change if you enable/disable serial functionality in this app and change this in your original firmware ;)

![screenshot from 2019-02-13 11-15-36](https://user-images.githubusercontent.com/4346464/52704521-0d2f4880-2f81-11e9-8d3e-b9bb279df183.png)

**Comment by tomaskovacik** [comment]
I try it and failed ...

**Comment by DrSaad77** [comment]
> I've written the firmware bin file to a BK8000L module to get AT commands working, and am finding that I'm getting a battery low warning on connection with an android device. This did not happen previously. Is there any reference of hex values to change for configuring these various features? As a battery warning message is not helpful on a non-battery powered device, such as in a car radio.

Dont know much about AT command meaning, anyway I was getting same issue first time, I connect my BK8000L to a 3.3V supply. Was wondering WTF, everywhere I read, 3.3V is what is needed!! Then I started to increase gradually to 4.2V, still 4.2v (lithium Battery) was giving me 80% capacity. Then to 5V to then 100% !!!
I read somewhere that 5V is ok, except module get hot, so came back to 4.2V, and now at 4.2V giving me 100% capacity reading 😳
I know crazy right?? 
To resolve warning battery, feed the module with 4.2V or 5V. And dont bother on software part for that 😉
