### ISSUE TITLE
Flash the firmware to BK3254

### ISSUE THREAD

**Issue by glololou** [tomaskovacik/kicad-library#5]
I have a bk3254 and I want to flash this bluetooth module to custom sound effect , but I don't know how do It from BK3254 ToolKit, please help me. What I need to do to flash this?

**Comment by tomaskovacik** [comment]
sorry mate I cant help you, I have same information as you have (all docs are in this repo) if you are not able to find it in there, then I was also not :(

**Comment by tomaskovacik** [comment]
duplicate #6
