### ISSUE TITLE
upload/download custom firmware to BK3254

### ISSUE THREAD

**Issue by DanteBC** [tomaskovacik/kicad-library#6]
Hello, Tomas. 
I've been experimenting with BK3254 Module and noticed "custom voicelines" tab in the toolkit. Is it really possible to upload custom event sounds to that module? Should I use jtag for it?

**Comment by tomaskovacik** [comment]
based on dates:

bk8000L datasheet version 0.1 is from 10/May/2014

and this article is from 02.06.2014 ( https://www.beyondsemi.com/15/clanek/beken-chooses-ba22-processor-to-satisfy-tight-constraints-in-new-mobile-bluetooth-audio-chip/25/ )

 I'm sure bk8000L is not BA22 based 


 only BK3254X use beyond semi chips (32bit MCU BA22)

https://oss.aliyuncs.com/netmarket/02473ec1-1155-458b-85b8-275343641532.pdf

3.6.
MCU
The BK3254X includes a 32-bit internal RISC MCU with 32 kB Instruction-Cache,
112 kB data RAM, and a DMA bus controller to run the Bluetooth software stack
and application while supporting efficient execution and data exchange with the
internal SIP FLASH memory. The JTAG interface can be used for on-line debug
and can also be configured as GPIO.

**Comment by sergek** [comment]
Hi, Tomas, according to this blog post bk8000l is BA22
http://kovo-blog.blogspot.com/2019/10/connecting-jtag-to-bk8000l.html

**Comment by tomaskovacik** [comment]
thats my blog ;)On 7 Jan 2020 23:55, Sergey Kopalkin <notifications@github.com> wrote:Hi, Tomas, according to this blog post bk8000l is BA22
http://kovo-blog.blogspot.com/2019/10/connecting-jtag-to-bk8000l.html
