### ISSUE TITLE
HFP

### ISSUE THREAD

**Issue by xnatlive** [tomaskovacik/kicad-library#7]
Hello
I'm building a sound system with this module controlled by atmega328p I wonder is it possible to disable phone call and use module as only music player

**Comment by tomaskovacik** [comment]
posibly better discution repo is this because only solution is really custom firmware/configuration

**Comment by xnatlive** [comment]
thank you.
about custom firmware, because I have more than 200 pieces of the module marked(F-6888, V1.2 2016-8-6) do you think its possible to change the firmware on them.
I have decent electronic lab and I'm looking for solution to make those use full

**Comment by tomaskovacik** [comment]
I do not know, chceck issue #6
