### ISSUE TITLE
is there a way to change its name using at command?

### ISSUE THREAD

**Issue by Wachenanggo** [tomaskovacik/kicad-library#9]

**Comment by tomaskovacik** [comment]
which module?

**Comment by Wachenanggo** [comment]
BK8000l

**Comment by tomaskovacik** [comment]
Unfortunetly no, check my blog:http://kovo-blog.blogspot.com/2017/11/bk8000l-change-name.html?m=1On 6 May 2020 15:56, Wachenanggo <notifications@github.com> wrote:
BK8000l
